import re

from fastapi import APIRouter, HTTPException

from app.models import (
    RAGRequest,
    RAGResponse,
    EvidenceNode,
    EvidenceRelationship,
)

from app.neo4j_client import Neo4jClient
from app.retrieval import GraphRetriever
from app.prompt_builder import PromptBuilder
from app.ollama_client import OllamaClient


router = APIRouter(
    tags=["RAG"]
)


neo4j_client = Neo4jClient()

retriever = GraphRetriever(
    neo4j_client
)

ollama = OllamaClient()


# ============================================================
# CONSTANTS
# ============================================================

KNOWN_SERVICES = [
    "event-service",
    "device-service",
    "auth-service",
    "gateway",
    "api-gateway",
    "soc-service",
    "rag-service",
]

KNOWN_USERS = [
    "admin",
    "administrator",
    "user",
]

KNOWN_THREATS = [
    "brute force",
    "password spraying",
    "broken object level authorization",
    "unrestricted resource consumption",
]

KNOWN_CONTROLS = [
    "account lockout",
    "mfa",
    "multi-factor authentication",
    "password reset",
    "ip blocking",
]


# ============================================================
# TEXT HELPERS
# ============================================================

def contains_any(
    text: str,
    values: list[str]
) -> bool:

    return any(
        value in text
        for value in values
    )


# ============================================================
# INTENT DETECTION
# ============================================================

def detect_intent(
    question: str
) -> str:
    """
    Determine which graph retrieval operation should be used.

    The classifier intentionally remains deterministic so that
    retrieval behaviour is predictable and easy to demonstrate.

    Supported intents:

        alert_investigation
        alert_threat
        alert_response
        alert_service

        user_events
        user_alerts

        event_investigation
        event_alerts
        event_user

        threat_investigation
        threat_alerts
        threat_controls
        threat_vulnerabilities
        threat_response

        control_investigation
        control_threats

        service_dependencies
        service_investigation

        device_events
        device_alerts

        vulnerability_investigation
        response_investigation

        security_overview
    """

    q = question.lower().strip()

    # ========================================================
    # ALERTS
    # ========================================================

    if "alert-" in q:

        # Controls / mitigation take priority.
        if contains_any(
            q,
            [
                "control",
                "controls",
                "mitigate",
                "mitigates",
                "mitigation",
                "prevent",
                "prevention",
                "protect",
            ]
        ):
            return "threat_controls"

        # Response / remediation.
        if contains_any(
            q,
            [
                "response",
                "respond",
                "remediation",
                "remediate",
                "what should i do",
                "what should be done",
                "how should i respond",
                "how do i respond",
            ]
        ):
            return "alert_response"

        # Threat / attack.
        if contains_any(
            q,
            [
                "threat",
                "attack",
                "technique",
                "mitre",
                "owasp",
            ]
        ):
            return "alert_threat"

        # Service association.
        if contains_any(
            q,
            [
                "service",
                "services",
                "generated by",
                "came from",
            ]
        ):
            return "alert_service"

        # Events / evidence / investigation.
        if contains_any(
            q,
            [
                "event",
                "events",
                "caused",
                "cause",
                "created",
                "triggered",
                "evidence",
                "investigate",
                "investigation",
                "why",
                "happen",
                "happened",
                "generated",
                "details",
                "information",
                "explain",
                "explanation",
            ]
        ):
            return "alert_investigation"

        # Default for a question containing a specific alert.
        return "alert_investigation"

    # ========================================================
    # EVENTS
    # ========================================================

    if "event-" in q:

        if contains_any(
            q,
            [
                "alert",
                "alerts",
                "created",
                "caused",
                "associated",
                "resulted",
            ]
        ):
            return "event_alerts"

        if contains_any(
            q,
            [
                "user",
                "who",
                "account",
                "actor",
            ]
        ):
            return "event_user"

        return "event_investigation"

    # ========================================================
    # USERS
    # ========================================================

    if contains_any(
        q,
        [
            "user",
            "username",
            "account",
            "actor",
        ]
    ):

        if contains_any(
            q,
            [
                "alert",
                "alerts",
            ]
        ):
            return "user_alerts"

        if contains_any(
            q,
            [
                "event",
                "events",
                "activity",
                "activities",
                "actions",
                "login",
                "logins",
            ]
        ):
            return "user_events"

    # ========================================================
    # THREATS
    # ========================================================

    if contains_any(
        q,
        [
            "threat",
            "threats",
            "attack technique",
            "attack techniques",
            "mitre",
            "owasp",
            "brute force",
            "password spraying",
            "broken object level authorization",
            "unrestricted resource consumption",
        ]
    ):

        if contains_any(
            q,
            [
                "control",
                "controls",
                "mitigate",
                "mitigation",
                "prevent",
                "prevention",
                "protect",
            ]
        ):
            return "threat_controls"

        if contains_any(
            q,
            [
                "vulnerability",
                "vulnerabilities",
                "cwe",
                "cve",
            ]
        ):
            return "threat_vulnerabilities"

        if contains_any(
            q,
            [
                "response",
                "respond",
                "remediation",
                "procedure",
                "procedures",
                "incident response",
            ]
        ):
            return "threat_response"

        if contains_any(
            q,
            [
                "alert",
                "alerts",
            ]
        ):
            return "threat_alerts"

        return "threat_investigation"

    # ========================================================
    # CONTROLS
    # ========================================================

    if contains_any(
        q,
        [
            "control",
            "controls",
            "security control",
            "security controls",
        ]
    ):

        if contains_any(
            q,
            [
                "threat",
                "threats",
                "attack",
                "attacks",
            ]
        ):
            return "control_threats"

        return "control_investigation"

    # ========================================================
    # SERVICES
    # ========================================================

    if contains_any(
        q,
        [
            "service",
            "services",
            "microservice",
            "microservices",
        ]
    ):

        if contains_any(
            q,
            [
                "depend",
                "dependency",
                "dependencies",
                "affected",
                "impact",
                "fails",
                "fail",
                "failure",
                "down",
                "relies",
                "rely",
                "relies on",
            ]
        ):
            return "service_dependencies"

        return "service_investigation"

    # ========================================================
    # DEVICES
    # ========================================================

    if contains_any(
        q,
        [
            "device",
            "devices",
            "iot device",
            "iot devices",
        ]
    ):

        if contains_any(
            q,
            [
                "alert",
                "alerts",
            ]
        ):
            return "device_alerts"

        return "device_events"

    # ========================================================
    # VULNERABILITIES
    # ========================================================

    if contains_any(
        q,
        [
            "vulnerability",
            "vulnerabilities",
            "cwe-",
            "cve-",
        ]
    ):
        return "vulnerability_investigation"

    # ========================================================
    # RESPONSE PROCEDURES
    # ========================================================

    if contains_any(
        q,
        [
            "response procedure",
            "response procedures",
            "incident response",
            "remediation procedure",
            "remediation procedures",
        ]
    ):
        return "response_investigation"

    # ========================================================
    # GENERAL SECURITY QUESTIONS
    # ========================================================

    return "security_overview"


# ============================================================
# ID / ENTITY EXTRACTION
# ============================================================

def extract_alert_id(
    question: str
):

    match = re.search(
        r"\balert-\d+\b",
        question.lower()
    )

    if match:
        return match.group(0)

    return None


def extract_event_id(
    question: str
):

    match = re.search(
        r"\bevent-\d+\b",
        question.lower()
    )

    if match:
        return match.group(0)

    return None


def extract_user_id(
    question: str
):

    q = question.lower()

    # Explicit user identifiers.
    match = re.search(
        r"\buser[-_]?[a-zA-Z0-9]+\b",
        q
    )

    if match:
        return match.group(0)

    # Known usernames.
    for user in KNOWN_USERS:

        if re.search(
            rf"\b{re.escape(user)}\b",
            q
        ):
            return user

    return None


def extract_service_name(
    question: str
):

    q = question.lower()

    for service in KNOWN_SERVICES:

        if service in q:
            return service

    return None


def extract_device_id(
    question: str
):
    """
    Extract an IoT device identifier.

    Supported examples:

        IOT-001
        IOT-002
        iot-001
        DEVICE-001
        device-001
        device_001
    """

    q = question.lower()

    patterns = [
        r"\biot-\d+\b",
        r"\bdevice-\d+\b",
        r"\bdevice_\d+\b",
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            q
        )

        if match:

            return match.group(0).upper()

    return None


def extract_threat_name(
    question: str
):

    q = question.lower()

    for threat in KNOWN_THREATS:

        if threat in q:
            return threat

    return None


def extract_control_name(
    question: str
):

    q = question.lower()

    for control in KNOWN_CONTROLS:

        if control in q:
            return control

    return None


# ============================================================
# NEO4J NODE CONVERSION
# ============================================================

def convert_node(node):
    """
    Convert a Neo4j Node or dictionary into the normalized
    EvidenceNode format expected by the RAG API.

    Output:

        {
            "id": "...",
            "label": "...",
            "properties": {...}
        }
    """

    if node is None:
        return None

    # ========================================================
    # DICTIONARY
    # ========================================================

    if isinstance(node, dict):

        labels = node.get(
            "labels",
            []
        )

        properties = node.get(
            "properties",
            {}
        )

        # If this is a plain property dictionary,
        # treat all fields as properties.
        if not properties:

            properties = {
                key: value
                for key, value in node.items()
                if key not in {
                    "id",
                    "label",
                    "labels",
                }
            }

        # Normalize labels.
        if isinstance(
            labels,
            str
        ):

            label = labels

        elif labels:

            label = str(
                labels[0]
            )

        else:

            label = (
                node.get("label")
                or "Node"
            )

        # Stable business identifier.
        node_id = (
            node.get("id")
            or properties.get("alertId")
            or properties.get("eventId")
            or properties.get("userId")
            or properties.get("deviceId")
            or properties.get("serviceId")
            or properties.get("vulnerabilityId")
            or properties.get("procedureId")
            or properties.get("controlId")
            or properties.get("name")
        )

        return {
            "id": (
                str(node_id)
                if node_id is not None
                else None
            ),
            "label": label,
            "properties": properties,
        }

    # ========================================================
    # NATIVE NEO4J NODE
    # ========================================================

    labels = list(
        node.labels
    )

    properties = dict(
        node
    )

    node_id = (
        properties.get("alertId")
        or properties.get("eventId")
        or properties.get("userId")
        or properties.get("deviceId")
        or properties.get("serviceId")
        or properties.get("vulnerabilityId")
        or properties.get("procedureId")
        or properties.get("controlId")
        or properties.get("name")
        or str(node.id)
    )

    label = (
        str(labels[0])
        if labels
        else "Node"
    )

    return {
        "id": str(node_id),
        "label": label,
        "properties": properties,
    }


# ============================================================
# RELATIONSHIP CONVERSION
# ============================================================

def convert_relationship(
    relationship
):

    if not relationship:
        return None

    # --------------------------------------------------------
    # Dictionary representation
    # --------------------------------------------------------

    if isinstance(
        relationship,
        dict
    ):

        source = relationship.get(
            "source"
        )

        target = relationship.get(
            "target"
        )

        relation = relationship.get(
            "relationship"
        )

        if not source or not target or not relation:
            return None

        return EvidenceRelationship(
            source=str(source),
            relationship=str(relation),
            target=str(target)
        )

    # --------------------------------------------------------
    # Native Neo4j relationship
    # --------------------------------------------------------

    try:

        relation_type = (
            relationship.type
        )

        source = (
            relationship.start_node
        )

        target = (
            relationship.end_node
        )

        source_node = convert_node(
            source
        )

        target_node = convert_node(
            target
        )

        if not source_node or not target_node:
            return None

        return EvidenceRelationship(
            source=str(
                source_node["id"]
            ),
            relationship=str(
                relation_type
            ),
            target=str(
                target_node["id"]
            )
        )

    except Exception:
        return None


# ============================================================
# GENERIC EVIDENCE BUILDER
# ============================================================

def build_generic_evidence(
    records
):
    """
    Normalize Neo4j retrieval results into the API's
    EvidenceNode and EvidenceRelationship structures.

    This replaces the need for a separate evidence builder
    for every retrieval intent.
    """

    nodes = []
    relationships = []

    node_ids = set()
    relationship_ids = set()

    # ========================================================
    # NODE KEYS
    # ========================================================

    node_keys = {
        "alert",
        "alerts",

        "event",
        "events",

        "user",
        "users",

        "threat",
        "threats",

        "control",
        "controls",

        "service",
        "services",

        "failed",

        "affected_services",

        "device",
        "devices",

        "vulnerability",
        "vulnerabilities",

        "procedure",
        "procedures",

        "response_procedure",
        "response_procedures",

        "dependent",
        "dependents",

        "dependency",
        "dependencies",
    }

    # ========================================================
    # RELATIONSHIP KEYS
    # ========================================================

    relationship_keys = {
        "event_alert_relationships",
        "user_event_relationships",
        "alert_threat_relationships",
        "control_threat_relationships",
        "dependency_relationships",
        "vulnerability_threat_relationships",
        "procedure_relationships",
        "threat_control_relationships",
        "threat_alert_relationships",
        "event_user_relationships",
        "device_event_relationships",
        "device_alert_relationships",
    }

    # ========================================================
    # RECORDS
    # ========================================================

    for record in records:

        if not isinstance(
            record,
            dict
        ):
            continue

        # ----------------------------------------------------
        # NODES
        # ----------------------------------------------------

        for key in node_keys:

            value = record.get(
                key
            )

            if value is None:
                continue

            if not isinstance(
                value,
                list
            ):
                value = [value]

            for item in value:

                if not item:
                    continue

                node = convert_node(
                    item
                )

                if not node:
                    continue

                node_id = node.get(
                    "id"
                )

                if (
                    node_id is not None
                    and node_id not in node_ids
                ):

                    nodes.append(
                        node
                    )

                    node_ids.add(
                        node_id
                    )

        # ----------------------------------------------------
        # RELATIONSHIPS
        # ----------------------------------------------------

        for key in relationship_keys:

            value = record.get(
                key
            )

            if not value:
                continue

            # Flatten nested relationship lists.
            flattened = []

            if isinstance(
                value,
                list
            ):

                for item in value:

                    if isinstance(
                        item,
                        list
                    ):

                        flattened.extend(
                            item
                        )

                    else:

                        flattened.append(
                            item
                        )

            else:

                flattened.append(
                    value
                )

            for item in flattened:

                relationship = (
                    convert_relationship(
                        item
                    )
                )

                if not relationship:
                    continue

                relationship_key = (
                    relationship.source,
                    relationship.relationship,
                    relationship.target
                )

                if (
                    relationship_key
                    not in relationship_ids
                ):

                    relationships.append(
                        relationship
                    )

                    relationship_ids.add(
                        relationship_key
                    )

    return nodes, relationships


# ============================================================
# EVIDENCE TEXT FOR QWEN3
# ============================================================

def evidence_to_text(
    nodes,
    relationships
):
    """
    Convert normalized graph evidence into a compact,
    structured text representation for Qwen3.
    """

    lines = []

    # ========================================================
    # NODES
    # ========================================================

    if nodes:

        lines.append(
            "NODES:"
        )

        for node in nodes:

            if not isinstance(
                node,
                dict
            ):
                continue

            node_id = node.get(
                "id"
            )

            label = node.get(
                "label",
                "Node"
            )

            properties = node.get(
                "properties",
                {}
            )

            lines.append(
                f"- {label} "
                f"(id={node_id}): "
                f"{properties}"
            )

    # ========================================================
    # RELATIONSHIPS
    # ========================================================

    if relationships:

        lines.append("")

        lines.append(
            "RELATIONSHIPS:"
        )

        for relationship in relationships:

            if isinstance(
                relationship,
                dict
            ):

                source = relationship.get(
                    "source"
                )

                relationship_type = (
                    relationship.get(
                        "relationship"
                    )
                )

                target = relationship.get(
                    "target"
                )

            else:

                source = (
                    relationship.source
                )

                relationship_type = (
                    relationship.relationship
                )

                target = (
                    relationship.target
                )

            lines.append(
                f"- {source} "
                f"-[{relationship_type}]-> "
                f"{target}"
            )

    if not lines:

        return (
            "No graph evidence was retrieved."
        )

    return "\n".join(lines)


# ============================================================
# EVIDENCE SUMMARY
# ============================================================

def build_evidence_summary(
    nodes,
    relationships
):

    return (
        f"Retrieved {len(nodes)} nodes and "
        f"{len(relationships)} relationships "
        f"from the Neo4j knowledge graph."
    )


# ============================================================
# RETRIEVAL DISPATCHER
# ============================================================

def retrieve_for_intent(
    intent: str,
    question: str
):
    """
    Resolve the detected intent into the appropriate
    GraphRetriever operation.
    """

    alert_id = extract_alert_id(
        question
    )

    event_id = extract_event_id(
        question
    )

    user_id = extract_user_id(
        question
    )

    service_name = extract_service_name(
        question
    )

    device_id = extract_device_id(
        question
    )

    threat_name = extract_threat_name(
        question
    )

    control_name = extract_control_name(
        question
    )

    # ========================================================
    # ALERT INVESTIGATION
    # ========================================================

    if intent == "alert_investigation":

        if not alert_id:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify an alert ID."
                )
            )

        return retriever.retrieve_alert_investigation(
            alert_id
        )

    # ========================================================
    # ALERT THREAT
    # ========================================================

    if intent == "alert_threat":

        if not alert_id:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify an alert ID."
                )
            )

        return retriever.retrieve_alert_investigation(
            alert_id
        )

    # ========================================================
    # ALERT RESPONSE
    # ========================================================

    if intent == "alert_response":

        if not alert_id:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify an alert ID."
                )
            )

        # The alert investigation already traverses:
        #
        # Alert -> Threat -> Control
        #
        # and therefore provides useful response context.
        #
        # If a dedicated alert-response retriever is added
        # later, this branch can be switched to it.

        return retriever.retrieve_alert_investigation(
            alert_id
        )

    # ========================================================
    # ALERT SERVICE
    # ========================================================

    if intent == "alert_service":

        if not alert_id:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify an alert ID."
                )
            )

        return retriever.retrieve_alert_investigation(
            alert_id
        )

    # ========================================================
    # THREAT CONTROLS
    # ========================================================

    if intent == "threat_controls":

        if alert_id:

            return retriever.retrieve_threat_controls(
                alert_id
            )

        if threat_name:

            # Requires retrieve_threat_controls_by_name()
            # in GraphRetriever.
            if hasattr(
                retriever,
                "retrieve_threat_controls_by_name"
            ):

                return (
                    retriever
                    .retrieve_threat_controls_by_name(
                        threat_name
                    )
                )

            # Fall back to general threat investigation
            # if the dedicated method does not yet exist.
            return (
                retriever
                .retrieve_threat_investigation(
                    threat_name
                )
            )

        raise HTTPException(
            status_code=400,
            detail=(
                "Could not identify an alert or threat."
            )
        )

    # ========================================================
    # USER EVENTS
    # ========================================================

    if intent == "user_events":

        if not user_id:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify a user."
                )
            )

        return retriever.retrieve_user_events(
            user_id
        )

    # ========================================================
    # USER ALERTS
    # ========================================================

    if intent == "user_alerts":

        if not user_id:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify a user."
                )
            )

        return retriever.retrieve_user_alerts(
            user_id
        )

    # ========================================================
    # EVENT INVESTIGATION
    # ========================================================

    if intent == "event_investigation":

        if not event_id:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify an event ID."
                )
            )

        return retriever.retrieve_event_investigation(
            event_id
        )

    # ========================================================
    # EVENT ALERTS
    # ========================================================

    if intent == "event_alerts":

        if not event_id:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify an event ID."
                )
            )

        return retriever.retrieve_event_investigation(
            event_id
        )

    # ========================================================
    # EVENT USER
    # ========================================================

    if intent == "event_user":

        if not event_id:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify an event ID."
                )
            )

        return retriever.retrieve_event_investigation(
            event_id
        )

    # ========================================================
    # THREAT INVESTIGATION
    # ========================================================

    if intent == "threat_investigation":

        if not threat_name:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify a threat."
                )
            )

        return retriever.retrieve_threat_investigation(
            threat_name
        )

    # ========================================================
    # THREAT ALERTS
    # ========================================================

    if intent == "threat_alerts":

        if not threat_name:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify a threat."
                )
            )

        return retriever.retrieve_threat_alerts(
            threat_name
        )

    # ========================================================
    # THREAT VULNERABILITIES
    # ========================================================

    if intent == "threat_vulnerabilities":

        if not threat_name:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify a threat."
                )
            )

        return (
            retriever
            .retrieve_threat_vulnerabilities(
                threat_name
            )
        )

    # ========================================================
    # THREAT RESPONSE
    # ========================================================

    if intent == "threat_response":

        if not threat_name:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify a threat."
                )
            )

        return retriever.retrieve_threat_response(
            threat_name
        )

    # ========================================================
    # CONTROL INVESTIGATION
    # ========================================================

    if intent == "control_investigation":

        if not control_name:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify a security control."
                )
            )

        if hasattr(
            retriever,
            "retrieve_control_investigation"
        ):

            return (
                retriever
                .retrieve_control_investigation(
                    control_name
                )
            )

        raise HTTPException(
            status_code=501,
            detail=(
                "Control investigation retrieval "
                "is not implemented yet."
            )
        )

    # ========================================================
    # CONTROL THREATS
    # ========================================================

    if intent == "control_threats":

        if not control_name:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify a security control."
                )
            )

        if hasattr(
            retriever,
            "retrieve_control_threats"
        ):

            return (
                retriever
                .retrieve_control_threats(
                    control_name
                )
            )

        raise HTTPException(
            status_code=501,
            detail=(
                "Control threat retrieval "
                "is not implemented yet."
            )
        )

    # ========================================================
    # SERVICE DEPENDENCIES
    # ========================================================

    if intent == "service_dependencies":

        if not service_name:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify "
                    "the service name."
                )
            )

        return (
            retriever
            .retrieve_service_dependencies(
                service_name
            )
        )

    # ========================================================
    # SERVICE INVESTIGATION
    # ========================================================

    if intent == "service_investigation":

        if not service_name:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify "
                    "the service name."
                )
            )

        return (
            retriever
            .retrieve_service_investigation(
                service_name
            )
        )

    # ========================================================
    # DEVICE EVENTS
    # ========================================================

    if intent == "device_events":

        if not device_id:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify "
                    "the device ID."
                )
            )

        return retriever.retrieve_device_events(
            device_id
        )

    # ========================================================
    # DEVICE ALERTS
    # ========================================================

    if intent == "device_alerts":

        if not device_id:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Could not identify "
                    "the device ID."
                )
            )

        return retriever.retrieve_device_alerts(
            device_id
        )

    # ========================================================
    # VULNERABILITY
    # ========================================================

    if intent == "vulnerability_investigation":

        if hasattr(
            retriever,
            "retrieve_vulnerability_investigation"
        ):

            return (
                retriever
                .retrieve_vulnerability_investigation(
                    question
                )
            )

        raise HTTPException(
            status_code=501,
            detail=(
                "Vulnerability retrieval "
                "is not implemented yet."
            )
        )

    # ========================================================
    # RESPONSE PROCEDURES
    # ========================================================

    if intent == "response_investigation":

        if hasattr(
            retriever,
            "retrieve_response_procedures"
        ):

            return (
                retriever
                .retrieve_response_procedures(
                    question
                )
            )

        raise HTTPException(
            status_code=501,
            detail=(
                "Response procedure retrieval "
                "is not implemented yet."
            )
        )

    # ========================================================
    # SECURITY OVERVIEW
    # ========================================================

    if intent == "security_overview":

        if hasattr(
            retriever,
            "retrieve_security_overview"
        ):

            return (
                retriever
                .retrieve_security_overview()
            )

        raise HTTPException(
            status_code=501,
            detail=(
                "General security overview retrieval "
                "is not implemented yet."
            )
        )

    # ========================================================
    # UNKNOWN
    # ========================================================

    raise HTTPException(
        status_code=400,
        detail=(
            f"Unsupported retrieval intent: {intent}"
        )
    )


# ============================================================
# MAIN RAG ENDPOINT
# ============================================================

@router.post(
    "/ask",
    response_model=RAGResponse
)
def ask_rag(
    request: RAGRequest
):

    # ========================================================
    # VALIDATE QUESTION
    # ========================================================

    question = request.question.strip()

    if not question:

        raise HTTPException(
            status_code=400,
            detail="Question cannot be empty."
        )

    # ========================================================
    # DETECT INTENT
    # ========================================================

    intent = detect_intent(
        question
    )

    # ========================================================
    # RETRIEVE GRAPH EVIDENCE
    # ========================================================

    try:

        records = retrieve_for_intent(
            intent,
            question
        )

    except HTTPException:
        raise

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=(
                "Neo4j graph retrieval failed: "
                f"{exc}"
            )
        )

    if records is None:
        records = []

    # ========================================================
    # NORMALIZE EVIDENCE
    # ========================================================

    nodes, relationships = (
        build_generic_evidence(
            records
        )
    )

    # ========================================================
    # NO EVIDENCE
    # ========================================================

    if not nodes:

        answer = (
            "The knowledge graph did not return "
            "evidence relevant to this question."
        )

        return RAGResponse(
            question=question,
            intent=intent,
            answer=answer,
            retrieval_method=(
                "Cypher graph traversal"
            ),
            evidence_nodes=[],
            evidence_relationships=[],
            evidence_count=0,
            grounding=(
                "No relevant Neo4j evidence "
                "was retrieved."
            ),
            evidence_summary=(
                "No evidence was retrieved."
            )
        )

    # ========================================================
    # CONVERT EVIDENCE TO TEXT
    # ========================================================

    evidence_text = evidence_to_text(
        nodes,
        relationships
    )

    # ========================================================
    # BUILD QWEN3 PROMPT
    # ========================================================

    prompt = PromptBuilder.build(
        question=question,
        intent=intent,
        evidence=evidence_text
    )

    # ========================================================
    # QWEN3 GENERATION
    # ========================================================

    try:

        answer = ollama.generate(
            prompt
        )

    except Exception as exc:

        raise HTTPException(
            status_code=502,
            detail=(
                "Qwen3/Ollama generation failed: "
                f"{exc}"
            )
        )

    # ========================================================
    # RESPONSE
    # ========================================================

    evidence_count = (
        len(nodes)
        + len(relationships)
    )

    return RAGResponse(
        question=question,
        intent=intent,
        answer=answer,
        retrieval_method=(
            "Cypher graph traversal + Qwen3"
        ),
        evidence_nodes=nodes,
        evidence_relationships=relationships,
        evidence_count=evidence_count,
        grounding=(
            "The response was generated from "
            "retrieved Neo4j graph evidence."
        ),
        evidence_summary=(
            build_evidence_summary(
                nodes,
                relationships
            )
        )
    )