# =========================================================
# APPLICATION
# =========================================================

spring:
  application:
    name: api-gateway


  # =======================================================
  # SPRING CLOUD GATEWAY
  # =======================================================

  cloud:
    gateway:
      server:
        webflux:

          # -------------------------------------------------
          # ROUTES
          # -------------------------------------------------

          routes:

            # =================================================
            # DEVICE SERVICE
            # =================================================

            - id: device-service

              uri: lb://device-service

              predicates:
                - Path=/api/devices/**


            # =================================================
            # EVENT SERVICE
            # =================================================

            - id: event-service

              uri: lb://event-service

              predicates:
                - Path=/api/events/**


            # =================================================
            # AUTH SERVICE
            # =================================================

            - id: auth-service

              uri: lb://auth-service

              predicates:
                - Path=/api/auth/**


# =========================================================
# SERVER
# =========================================================

server:
  port: ${SERVER_PORT:8090}


# =========================================================
# JWT
# =========================================================

jwt:
  secret: ${JWT_SECRET:change-this-development-secret-key-1234567890}


# =========================================================
# EUREKA CLIENT
# =========================================================

eureka:
  client:

    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

    register-with-eureka: true

    fetch-registry: true

    registry-fetch-interval-seconds: 5

  instance:

    prefer-ip-address: true


# =========================================================
# ACTUATOR
# =========================================================

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway
          - metrics

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true


# =========================================================
# CIRCUIT BREAKER
# =========================================================

resilience4j:
  circuitbreaker:

    instances:

      eventServiceCircuitBreaker:

        registerHealthIndicator: true

        slidingWindowType: COUNT_BASED

        slidingWindowSize: 10

        minimumNumberOfCalls: 5

        failureRateThreshold: 50

        waitDurationInOpenState: 10s

        permittedNumberOfCallsInHalfOpenState: 3

        automaticTransitionFromOpenToHalfOpenEnabled: true


      deviceServiceCircuitBreaker:

        registerHealthIndicator: true

        slidingWindowType: COUNT_BASED

        slidingWindowSize: 10

        minimumNumberOfCalls: 5

        failureRateThreshold: 50

        waitDurationInOpenState: 10s

        permittedNumberOfCallsInHalfOpenState: 3

        automaticTransitionFromOpenToHalfOpenEnabled: true


# =========================================================
# LOGGING
# =========================================================

logging:

  file:
    name: ${LOGGING_FILE_NAME:/logs/gateway.log}

  structured:
    format:
      file: logstash

  level:

    root: INFO

    com.iotsecurity: INFO

    org.springframework.cloud.gateway: INFO

    org.springframework.security: INFO

    org.springframework.security.oauth2: INFO

    com.netflix.discovery: INFO

    org.springframework.cloud.loadbalancer: INFO