package com.iotsecurity.event.model;

public enum EventType {

    UNAUTHORIZED_ACCESS,
    FAILED_LOGIN,
    BRUTE_FORCE,
    MALWARE_DETECTED,
    SUSPICIOUS_NETWORK_ACTIVITY,
    PORT_SCAN,
    DEVICE_OFFLINE,
    DEVICE_TAMPERING,
    DATA_EXFILTRATION,
    ANOMALOUS_BEHAVIOR,
    POLICY_VIOLATION,
    OTHER
}