input {
    file {
        path => "/logs/*.log"
        start_position => "beginning"
        sincedb_path => "/tmp/logstash.sincedb"
        codec => json
    }
}

filter {
    mutate {
        add_field => {
            "environment" => "docker"
        }
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "iot-security-%{+YYYY.MM.dd}"
    }

    stdout {
        codec => rubydebug
    }
}