package com.iotsecurity.soc.controller;

import com.iotsecurity.soc.model.SOCAlert;
import com.iotsecurity.soc.repository.SOCAlertRepository;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/soc/alerts")
@Tag(
        name = "SOC Alerts",
        description = "Security alerts generated by SOC detection rules"
)
@SecurityRequirement(name = "bearerAuth")
public class AlertController {

    private static final Logger log =
            LoggerFactory.getLogger(AlertController.class);

    private final SOCAlertRepository alertRepository;

    public AlertController(SOCAlertRepository alertRepository) {
        this.alertRepository = alertRepository;
    }

    @GetMapping
    @Operation(
            summary = "Get all SOC alerts",
            description =
                    "Retrieves all security alerts generated by the SOC " +
                            "detection engine."
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "SOC alerts retrieved successfully"
            ),
            @ApiResponse(
                    responseCode = "401",
                    description = "Authentication required"
            ),
            @ApiResponse(
                    responseCode = "403",
                    description = "Access denied"
            )
    })
    public List<SOCAlert> getAlerts() {

        log.info("Retrieving all SOC alerts");

        List<SOCAlert> alerts =
                alertRepository.findAll();

        log.info(
                "Retrieved SOC alerts resultCount={}",
                alerts.size()
        );

        return alerts;
    }

    @GetMapping("/{id}")
    @Operation(
            summary = "Get a SOC alert by ID",
            description =
                    "Retrieves a specific SOC alert using its unique UUID."
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "SOC alert retrieved successfully"
            ),
            @ApiResponse(
                    responseCode = "401",
                    description = "Authentication required"
            ),
            @ApiResponse(
                    responseCode = "403",
                    description = "Access denied"
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "SOC alert not found"
            )
    })
    public SOCAlert getAlert(
            @PathVariable UUID id
    ) {

        log.info(
                "Retrieving SOC alert alertId={}",
                id
        );

        SOCAlert alert =
                alertRepository.findById(id)
                        .orElseThrow(() -> {

                            log.warn(
                                    "SOC alert not found alertId={}",
                                    id
                            );

                            return new RuntimeException(
                                    "SOC alert not found: " + id
                            );
                        });

        log.info(
                "SOC alert retrieved successfully alertId={} " +
                        "rule={} severity={} eventCount={}",
                alert.getId(),
                alert.getRule(),
                alert.getSeverity(),
                alert.getEventCount()
        );

        return alert;
    }
}